### PR TITLE
Pull requests/to/zer0kerbal/2020 0312

### PR DESCRIPTION
**Pull request by Lisias**
License unencumbered  (just in time) implementation for the EngineModuleWrapper.

Slightly faster, slightly more robust.

### CODE REVIEW

**Comment by Lisias** [comment]
I didn't tested this stunt properly yet. Please wait some time while I do such testings, I will advise here.

**Comment by zer0Kerbal** [comment]
thank you. saw you forked it and smiled. I would beta it anyways. :)
Enjoy the 13th!

**Comment by Lisias** [comment]
I rebased the pull request to allow a seamless merge on the main branch when appropriated.

I think it's working now, but I will spend this night toying around to be sure.

**Comment by zer0Kerbal** [comment]
Miu beuno! (hopefully spelled correctly)

Mucho gusto gracias!

**Comment by zer0Kerbal** [comment]
Holding pattern engaged. Once green lit I will revert the last commit with the poisoned pill, and merge in yours. Sounds like a plan.

**Comment by zer0Kerbal** [comment]
Again – thank you.

I will wait to hear from you before github:reset (never did that before) should be fun.

**Comment by Lisias** [comment]
It was not working! (pretty lame mistake, I need to work less and code more!) :D 

There's an additional advantage on this thing - it's pretty easily expandable, you want to support a new part, it's a new class and an additional IF on the right spot.

I'll try to support Firespitter before finishing it, and then I will check the engines from Breaking Ground.

**Comment by zer0Kerbal** [comment]
Saweet!

How about ODFC ? Can it / will it support ODFC? :D

**Comment by Lisias** [comment]
Damn, supporting Firespitter and Breaking Ground will need some additional changes on the OhScrap itself, so it's a bit out of the scope of the file this PR aims to work on.

Not big deal, but slightly less easy than I though. The same for Breaking Ground.

Supporting ODFC will be some more work - but not because ODFC, but because there's no FailureModule for converters. A whole new support code will be needed (Firespitter and BreakGroung engines are... engines, so the current support code can be tricked into handling them using the existing rules).

**Comment by Lisias** [comment]
In a way or another, the thing worked for StockModules. 90% of the stunt is good to go.

Ideally, I need to install SolverEngines and something that uses it, as well something using AJE .

If you already did tested OhScrap with them, then you should wait me to test them too.

If you never tried anything using them (and I think you didn't, as this stunt is new!), then this is good to go, as I trippled checked the AJE and Solver support and they do exactly the same procedures than the original, as well use the same identification method.

:)

**Comment by zer0Kerbal** [comment]
will continue to hold until you are satisfied 
do I still need to do a reset?

**Comment by zer0Kerbal** [comment]
Thank you to @Lisias 

merged manually. The code on the original pull request was already cherry-picked because a merge would resurrect the offending commit.

**Pull request closed without merging**
