### PR TITLE
Create zh-cn.cfg

### PR DESCRIPTION
**Pull request by ZhaoFJx**
Well...So, this is the Simplified Chinese localization file for the OhScrap. Hope all is correct ; )

Just pull a request to be merged and published as a patch

Signed-off-by: Jx <87643469+ZhaoFJx@users.noreply.github.com>

### CODE REVIEW

**Comment by zer0Kerbal** [comment]
thank you @ZhaoFJx 

closes # 63

**Review by zer0Kerbal — APPROVED** [review]
🧧

**Comment by ZhaoFJx** [comment]
So you're just sitting next to your computer refreshing Github? Why you are so fast XD

**Comment by zer0Kerbal** [comment]
> So you're just sitting next to your computer refreshing Github? Why you are so fast XD

just sat down to work on addons (three-to-four new adoptions this week for the holidays) and always have email in the background.

Plus (and more relevant - and more important) I respect the effort taken to provide a translation.

**Pull request merged**
