### PR TITLE
ModuleManager: patch in `ModuleUPFMEvents` during `LAST` pass instead of `AFTER`.

### LINKED ISSUE #46: OhScrap + RemoteTech = NREs and "Antenna Safety Rating: -1"
With RemoteTech installed, antennae are showing "Antenna Safety Rating: -1" in the right-click menus where the safety rating is shown. (Screenshot included). It's not clear what effect that may be having on failures, etc, but I haven't yet experienced an antenna failure since noticing this problem in. Antennae do not show this issue without RT installed.

Screenshot 2021-12-08 171757

Log files indicate NREs for OhScrap. [Player.log attached.](https://github.com/zer0Kerbal/OhScrap/files/7681749/Player.log)

Reproduced using only:
- KSP 1.12
- ModuleManager 4.2.1.0
- Scrapyard 2.2.0
- OhScrap 2.2.0
- RemoteTech 1.9.12

Thanks for maintaining this mod! Please let me know if you need any further information.

### LINKED ISSUE #91: [Bug 🐞]: NRE on game loading
### Brief description of your issue (aka the problem)

Upon loading the save that hasn't been played for 3 years game crashes

### Operating system

Windows 10

### KSP version

1.31.2

### Version of addon

2.2.99.0-<WHATEVER CHINESE CHARACTERS>

### Steps to reproduce the behavior or issue

1. Start game
2. Load game
3. Wait for it to load

### Expected behavior

1. Start game
2. Load game
3. Wait for it to load
4. Play game

### Actual behavior

1. Start game
2. Load game
3. Wait for it to load
4. Game crashes

### Environment

```shell
Mod: 2.2.99.0-<WHATEVER CHINESE CHARACTERS>
KSP: 1.31.2
Manual download from CurseForge because OverWolf/CurseForge application refuses to install
Relevant snippet from KSP.log in next portion.
```

### Log files

In KSP.log 1747 time the error:
```
[EXC 23:45:51.002] NullReferenceException: Object reference not set to an instance of an object
	OhScrap.BaseFailureModule.Initialize () (at <01ab19d437654295977ba3471f0631bc>:0)
	OhScrap.BaseFailureModule.FixedUpdate () (at <01ab19d437654295977ba3471f0631bc>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

### Screenshots

_No response_

### Additional context

Save has been untouched for 2+ years

### How did you download and install this?

CurseForge (download and manual installation)

### PR DESCRIPTION
**Pull request by keyspace**
Closes #46 as fixed.
Closes #91 as duplicate (might have comments that are different issues?..).

Some mods modify existing nodes/modules in parts, others replace them; sometimes this happens in a chained manner.

Not all parts fail the same way, too, so OhScrap adds different `*FailureModule`s across many files, often with rules on ordering, depending on which compatible mod is addressed.

In the touched ModuleManager patch, all parts that already have a `*FailureModule` also get a `ModuleUPFMEvents`.

Before this commit, RemoteTech antennas would get a `RTAntennaFailureModule` after the `ModuleUPFMEvents` patch has already run (and you don't get a second pass). This was because RemoteTech parts would only get their `*FailureModule` after getting a `ModuleRTAntenna`, different from antennas untouched by RT, which get a `*FailureModule` based on having a `ModuleDataTransmitter`, itself different from a custom `ModuleRTDataTransmitter`...

After this commit, parts having a `*FailureModule` are guaranteed to have a `ModuleUPFMEvents`. We do get a second pass!

This commit may also activate warranty and immediately expire it on all parts that were supposed to fail long ago, but were unable to communicate their intent to OhScrap.

More on ModuleManager patch ordering:

https://github.com/sarbian/ModuleManager/wiki/Patch-Ordering

### CODE REVIEW

**Comment by keyspace** [comment]
Testing - no display issues so far, no NREs...

image

**Review by zer0Kerbal — APPROVED** [review]
Nicely found! 🔎

**Comment by keyspace** [comment]
No new bugs or new NREs on "live" save so far.

image

(Pic: One new booster in tandem with four old ones.)

IMO worth mentioning on next release that some parts that "never used to fail" now "perform as advertised".

**Comment by zer0Kerbal** [comment]
> IMO worth mentioning on next release that some parts that "never used to fail" now "perform as advertised".

just plain deviously worded😂. I will mention that. 😁

**Comment by Bobisback** [comment]
Is this PR in the latest release? Does not look like it is? I am having the same issue?

Edit: Just looked, and it is not in the latest release, I just manually patched it.

**Pull request merged**
